# Generated by Django 4.2 on 2024-02-13 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_version_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('product_name',), 'permissions': [('change_published_status', 'Can cancel publication of a product'), ('change_product_description', 'Can change product description'), ('change_category', 'Can change category')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
